### ISSUE TITLE
Fade in Solid/Pulse

### ISSUE THREAD

**Issue by johnmastri** [DedeHai/FastLEDPainter#2]
Hey there - great library - is there a way to do a solid fill that fades in (no animation) or a pulse/heartbeat effect (no movement, only brightness)?

Thank you.

**Comment by DedeHai** [comment]
thanks,
this is an interesting question. Although it is possible to do this with the painter library, a solid fill with a fade-in / fade-out effect is easier to control by just setting the color of all pixels directly using the fastled command fill_solid() and then call this command in a loop where you adjust the brightness each time by a little bit. Let me know if you need help with that. There is an example of this command in use in the 'twinkly stars' demo animation in the examples folder.
The other way to do it using the library is to setup a brush with fade in & fade out (again, look at the twinkly star demo) and then painting all pixels before calling 'pixelcanvas.transfer()' and then just call pixelcanvas.transfer() and let it do the fading effect.
To paint all pixels at once goes something like this
```
 int i;
 pixelbrush.setSpeed(4096); //move by one pixel per call (subpixel speed is shifted by 12 bit)
 pixelbrush.setFadein(true); //fade in
 pixelbrush.setFadeout(true); //and fade out
 pixelbrush.moveTo(0) //move to first pixel
 //setup the color of the brush here, set it to zero brightness to make it fade in completeley
 
 //now paint all the pixels before transferring the canvas
 for (i = 0; i < numberofpixels; i++)
 {
     pixelbrush.paint(); //paint the brush to the canvas and move it to the next pixel
 }

 //now paint the canvas to the leds (this also does the fading of brightness at the same time)
 for (i = 0; i < 500; i++) //note: the number of calls required depends on fading speed
 {
      pixelcanvas.transfer(); //transfer (add) the canvas to the LEDs and update fade effects
      delay(10); //short delay to not make it too fast
 }
```
What this incomplete code snippet does is to paint each pixel with a color that fades in and then fades out. once it is faded out it stays that way until it is painted with this color again.
as you can see solid fading is doable but not so easy to have it under full control as you do not know when the fading is finished and the paint has to be applied again. it can be calculated from the fading speed though, a fading speed of 80 means fade by one value per call.
