### ISSUE TITLE
Individual fade in / fade out speeds

### ISSUE THREAD

**Issue by johnmastri** [DedeHai/FastLEDPainter#3]
Would be great to be able to adjust the fade in / fade out speeds individually!

**Comment by DedeHai** [comment]
individually as in different for each pixel? 
that can be done by adjusting the brush color before it paints a pixel. I do exactly that in the [sparkler demo](https://github.com/DedeHai/FastLEDPainter/blob/7ae344bee26537c61c5dcd4f8196fd6c232b5905/examples/ledstrip_animations/ledstrip_animations.ino#L102).
